### ISSUE TITLE
Scheme::inputs 配置问题

### ISSUE THREAD

**Issue by wiyr** [eleme/duang#29]
Scheme::inputs  要怎么配置，使得我点击编辑时，相关字段初始化时是有数据的，现在我点击编辑，数据都是空的，尽管后台是有数据的

**Comment by jiananshi** [comment]
后端返回的数据中要有 `id` 字段，之后 Duang 会往 `/:key/:id` 发送 GET 请求获取数据。还有问题可以贴上你的 duang.json 和后端返回数据再看一下
