### ISSUE TITLE
下一页按钮不能点击

### ISSUE THREAD

**Issue by wiyr** [eleme/duang#59]
从版本0.47 => 0.61后， 发现下一页按钮不能点击，呈灰色图案，但是我直接改url里面的page参数是可以跳到指定页面的，是我使用姿势不对吗

**Comment by YanagiEiichi** [comment]
是不是已经没有下一页了？

**Comment by wiyr** [comment]
有的，我发现0.0.60版本开始，下一页就不好使了

**Comment by YanagiEiichi** [comment]
一般情况下接口不会提供记录总数，设置 pageSize 后只有当前页的记录小于或等于 pageSize 才会显示「下一页」。

**Comment by YanagiEiichi** [comment]
0.0.60 之后，scheme 上设置 `"countable": true` 会调用列表资源后面的 count 路径来取记录总数。

比如原来有个列表接口是 `GET /api/mylist`，那么获取记录总数的接口就是 `GET /api/mylist/count`，这个接口直接返回一个记录总数的数值（外面不要包一个层）。

得到记录总数后分页器就可以显示出末页了，也不需要再依赖当前页的记录数来计算是否有下一页。

目前该功能处于试验阶段，后续稳定后再补文档。
