### ISSUE TITLE
HTML component show undefined with number values

### ISSUE THREAD

**Issue by Fity** [eleme/duang#72]
当 `componet: HTML` 时，如果 `value` 的值是 `int`(非`string`)，显示的时候会显示成 `undefined`.

config example:
```
{
"key": "field_id",
"component": "HTML",
"args": [{
    "args": "<b>{value}</b>"
}]
}
```

@jiananshi @YanagiEiichi

**Comment by jiananshi** [comment]
```js
{
  args: {
    html: "<b>{value}</b>"
  }
}
```

[文档](https://eleme.github.io/duang/docs/components/#Output%3A%3AHTML)

**Comment by Fity** [comment]
@jiananshi 服！
请告诉我 写了 `component: HTML` 和 不写 有什么区别？
